### ISSUE TITLE
What are the Deltas between the Nuget Packages?

### ISSUE THREAD

**Issue by Alois-xx** [microsoft/eventtracing-processing-samples#2]
Currently the latest version is 1.5.0. Do you have some release notes what has changed and what has been fixed?

**Comment by trgibeau** [comment]
Hi @Alois-xx, 

The 1.5.0 release contains bug fixes, I'll work with the team to make sure the release notes are available in future builds.

**Comment by trgibeau** [comment]
Hi @Alois-xx, 

Release notes are now embedded into the "All" Nuget package and can be seen on Nuget.org:
https://www.nuget.org/packages/Microsoft.Windows.EventTracing.Processing.All/

**Comment by Alois-xx** [comment]
Thanks Tristan. That helps. I hope the managed symbol load speed will improve also soon which is already something which is beeing worked on as far as I know. 

@trgibeau
