### ISSUE TITLE
NullReferenceException when reading Process of IContextSwitchIn

### ISSUE THREAD

**Issue by Alois-xx** [microsoft/eventtracing-processing-samples#3]
For some ETL files I get:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Windows.EventTracing.Cpu.ContextSwitchDataProvider.AllocatedContextSwitch.Microsoft.Windows.EventTracing.Cpu.IContextSwitchIn.get_Process()

Is this a known issue? I am using Nuget version 1.4.0. Is this already fixed with 1.5.0?

**Comment by trgibeau** [comment]
Hi @Alois-xx, 

We are not aware of the issue, could you share details on how the traces were collected?
May give insight into how the issue can occur.

**Comment by Alois-xx** [comment]
I have a large collection of ETL files with more than 20K of ETL files collected during automated tests. Some of them exhibit that problem. I can share an example file on a private channel.

**Comment by Alois-xx** [comment]
Thanks for fixing in 1.7.0! 
See Release Notes of
https://www.nuget.org/packages/Microsoft.Windows.EventTracing.Processing.All/
