### ISSUE TITLE
TraceProcessing 1.7.4 Is based on WPT with .NET Core

### ISSUE THREAD

**Issue by Alois-xx** [microsoft/eventtracing-processing-samples#4]
While it is nice to get newer features. The install size is enormous now. 

I created a self contained .NET Core 5.0 console application which needs ca. 70 MB. Now WPT comes with .NET Core 3.1 prepackaged which is another 80 MB. 

6/17/2021  05:16 PM        78,794,752 WPTx64 (DesktopEditions)-x86_en-us.msi
06/17/2021  05:16 PM         2,510,848 WPTx64 (OnecoreUAP)-x86_en-us.msi

In total my console application has now 150 MB where at least the self contained part of .NET Core is not necessary when you ship this as a library. The hosting application should define the used runtime and not every constituent should bring its own runtime with it.

**Comment by trgibeau** [comment]
@Alois-xx, 

The latest stable build of TraceProcessor library has a slimmed down version of the WPT, should hopefully reduce your application size.

Let us know if you continue to run into issues!
